### ISSUE TITLE
QrVectorLogo is not correctly scaled with non whole size

### ISSUE THREAD

**Issue by PhilipDukhov** [alexzhirkevich/custom-qr-generator#23] opened 2023-03-21 12:37 UTC
Library version: 1.6.0
Android version: 13

I'm using this simple vector image, that displays a circle
```xml
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="40dp"
    android:height="40dp"
    android:viewportWidth="40"
    android:viewportHeight="40">
    <path
        android:pathData="m0,20a20,20 0 0,1 40,0a20,20 0 0,1 -40,0z"
        android:fillColor="#000000" />
</vector>
```
When the size of the qr code view is not an integer - for example, I want it to take up part of the screen width, say 0.6, the logo is drawn rather pixelated. If I round up the size, it's drawn as it should be. Here is a sample code in Compose:
```kotlin
val textContent = LoremIpsum().values.first().take(300)
val context = LocalContext.current
val drawable = remember(textContent) {
    QrCodeDrawable(
        data = QrData.Text(textContent),
        options = QrVectorOptions.Builder()
            .setErrorCorrectionLevel(QrErrorCorrectionLevel.High)
            .setLogo(
                QrVectorLogo(
                    drawable = AppCompatResources.getDrawable(context, R.drawable.ic_logo),
                    padding = QrVectorLogoPadding.Natural(.28f),
                )
            )
            .setShapes(
                QrVectorShapes(
                    darkPixel = QrVectorPixelShape.RoundCorners(0.5f),
                    ball = QrVectorBallShape.Circle(1f),
                    frame = QrVectorFrameShape.Circle()
                )
            )
            .build(),
    )
}
Image(
    rememberDrawablePainter(drawable),
    contentDescription = null,
    contentScale = ContentScale.None,
    modifier = Modifier
        .size(300.5.dp)
)
```
Result with size `300.5.dp`: 

<img src="https://user-images.githubusercontent.com/6103621/226605984-2feefc1c-20cb-40c1-9c19-7dd534e430b6.png" width="300" />

Result with size `300.dp`: 

<img src="https://user-images.githubusercontent.com/6103621/226607736-d7618881-c382-4f24-966e-8bac5683509d.png" width="300" />

**Comment by alexzhirkevich** [comment] 2023-03-21 14:07
Hi, @PhilipDukhov.

Thanks for reporting, reproduced in 1.6.0. 

Can you please check if it reproduces in last snapshot `com.github.alexzhirkevich:custom-qr-generator:2019e393a3`. It seems to be fixed by itself  :)

**Comment by PhilipDukhov** [comment] 2023-03-21 14:18
@alexzhirkevich cool, looks like it's indeed fixed 😁

**Closed** 2023-03-22 08:43 UTC
Labels: bug
